### ISSUE TITLE
Tutorial does not compile

### ISSUE THREAD

**Issue by ctnimmo** [Phala-Network/phala-wiki#23]
Helloworld tutorial does not compile.

I've identified the issue as being the latest version of the Rust compiler (rustc 1.48.0 (7eac88abb 2020-11-16)) - it does not like braces on panic messages (as should be expected), but also has issues with Substrate as used in the helloworld branch (see https://github.com/paritytech/substrate/issues/7287).

I've already created a pull request for amendments to the basic tutorial. I thought that would be a better option than update the code (which ideally should not really change much - it's better to have the code fairly static rather than having to constantly update, test and inadvertently break it, thus putting users off at the first hurdle).

**Comment by ctnimmo** [comment]
My Pull request: https://github.com/Phala-Network/phala-wiki/pull/22

**Comment by ctnimmo** [comment]
@h4x3rotab and @Antoniaiaiaiaia perhaps you could check this - as it relates to our conversation on Discord (if the wiki is not updated then the code requires altering - but I believe, in this case, updating the docs would be the better option).

**Comment by h4x3rotab** [comment]
Closing because the problem has been fixed. Thanks a lot!

**Comment by jdrevon** [comment]
I have the same issue:

```
  error: panic message contains braces
     --> /home/user/phala-blockchain/ring/build.rs:376:71
      |
  376 |         panic!("One of the compatible llvm toolchain must exist: llvm-{11,10,9}");
      |                                                                       ^       ^
      |
  note: the lint level is defined here
     --> /home/user/phala-blockchain/ring/build.rs:32:5
      |
  32  |     warnings
      |     ^^^^^^^^
      = note: `#[forbid(non_fmt_panics)]` implied by `#[forbid(warnings)]`
      = note: this message is not used as a format string, but will be in Rust 2021
  help: add a "{}" format string to use the message literally
      |
  376 |         panic!("{}", "One of the compatible llvm toolchain must exist: llvm-{11,10,9}");
      |                +++++

  error: could not compile `ring` due to previous error
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed

```

I have the 11.1.0 version of llvm:

```
 llvm-config --version
11.1.0

```
And I've followed the updated tutorial. Maybe I've done something wrong?
