### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-wiki#32]
https://wiki.phala.network/en-us/docs/poc2/run-a-gatekeeper/faq    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/poc2/run-a-gatekeeper/maintain-nominator    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/gatekeeper/maintain-nominator    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/gatekeeper/faq    text/html; charset=utf-8    404    Not Found
https://wiki.polkadot.network/docs/en/maintain-nominator    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/pdiem/%20relref%20%22docs/pdiem/future-works.md%22%20    text/html; charset=utf-8    404    Not Found
https://github.com/Phala-Network/phala-blockchain/blob/master/pruntime/enclave/src/system/comp_election.rs    text/html; charset=utf-8    404    Not Found
https://polkadot.js.org/api/substrate/rpc.html    text/html; charset=utf-8    404    Not Found
https://www.notion.so/Claim-Test-Tokens-9f53f6b805634f84bd44f202ef53b11c    text/plain; charset=utf-8    404    Not Found
https://www.paka.fund/1    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/poc2/run-a-full-node/%5Bmaintain-guides-how-to-setup-sentry-node%5D(https://wiki.polkadot.network/docs/en/maintain-guides-how-to-setup-sentry-node)    text/html; charset=utf-8    404    Not Found
https://github.com/Phala-Network/phala-blockchain/blob/master/Dockerfile    text/html; charset=utf-8    404    Not Found
https://www.yuque.com/fagephalanetwork/phalatothemoon/kp0rv0    text/html; charset=utf-8    403    Forbidden
https://www.notion.so/Create-Accounts-710e6dccac6f45d2953f5ea84206a58e    text/plain; charset=utf-8    404    Not Found
https://www.yuque.com/books/share/da4b715a-83cd-43cb-b556-3cf891ec0164?    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/en-us/docs/developer/your-first-confidential-contract/Run-a-Local-Development-Network    text/html; charset=utf-8    404    Not Found
https://wiki.phala.network/zh-cn/docs/pdiem    text/html; charset=utf-8    404    Not Found

Credits to Phala Discord member Berto

**Comment by hey-berto** [comment]
Let me know if you need me to run the crawler again to verify the fixes 😊
