### ISSUE TITLE
How to increase confidence level

### ISSUE THREAD

**Issue by dennis8989** [Phala-Network/phala-wiki#40]
Hi sir
I had some problem about Intel SGX function.
my platform is Comet Lake with the latest BIOS version.
The confidence level is 4 now.
We want to meet confidence level 2.
Is there any suggestion to improve it?
Thanks.

**Comment by h4x3rotab** [comment]
Try this: https://wiki.phala.network/en-us/docs/poc3/4-faq/#viii-increase-confidence-level
