### ISSUE TITLE
How to configure and link Phala with tow servers or more

### ISSUE THREAD

**Issue by anter-faree** [Phala-Network/phala-wiki#42]
Hello, Thank you for providing us Phala Network.

I am new to Phala and I have read through the documentation to understand how to get started with it. I am very interested in using Phala and would like to know if it is possible to configure Phala for two servers or more? (i.e how to connect Phala to two servers or more?) Are there any articles that explain this step? I would appreciate any suggestion. 

Thank you in advance!

**Comment by shelvenzhou** [comment]
Hi there,

I don't really understand "connect Phala to two servers", but if you are trying to construct a mining pool containing multiple pRuntimes and single Phala node, you may use [Phala Runtime Bridge](https://wiki.phala.network/en-us/docs/prb/). 

You can join our [Discord channel](https://discord.gg/vCvGqcFZ) or [Telegram group](https://t.me/phalanetwork) for more help.

**Comment by h4x3rotab** [comment]
Closing for now. Feel free to reopen if there's any problem
