### ISSUE TITLE
"Certificate verification failed" when installing node

### ISSUE THREAD

**Issue by bmacer** [Phala-Network/phala-wiki#56]
in [1.2 Run a Local Development Network](https://github.com/Phala-Network/phala-wiki/blob/master/content/docs/developer/run-a-local-development-network.md) when installing node per 
```
curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g yarn
```
i encountered this error: 
```
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 23.222.5.133 443].
```

a quick search led me to [an answer](https://askubuntu.com/questions/1095266/apt-get-update-failed-because-certificate-verification-failed-because-handshake): `sudo apt install ca-certificates`.

if that's an acceptable solution, perhaps add it to the instructions?

**Comment by shelvenzhou** [comment]
Thank you, we have added `ca-certificates` to our build dependencies.
