### ISSUE TITLE
"error: failed to run custom build command for `openssl-sys v0.9.65`" following tutorial

### ISSUE THREAD

**Issue by bmacer** [Phala-Network/phala-wiki#57]
Basic AWS Ubuntu 20.04 installation, got:
```
error: failed to run custom build command for `openssl-sys v0.9.65`
```

during `cargo build --release`

resolution was in the error:
```
If you have OpenSSL installed you can likely fix this by
  installing `pkg-config`.
```

so `sudo apt-get pkg-config` fixed it.

not sure if it's desirable to include that in [the tutorial steps](https://github.com/Phala-Network/phala-wiki/blob/master/content/docs/developer/run-a-local-development-network.md#build-the-core-blockchain), but documenting in an issue anyway.

**Comment by shelvenzhou** [comment]
We have added `pkg-config` to our dependencies.
